version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: czat
    ports:
      - "5432:5432"
  backend:
    build: ./be
    container_name: backend
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/czat
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/czat
    depends_on:
      - mongo
      - postgres
    ports:
      - "8080:8080"
  frontend:
    build: ./fe
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
